import {summarizeProctorEvents,PROCTOR_EVENT_TYPES} from './proctoring.js';
export function installRemoteExams(app,{mongoose,User,Course,auth,audit,resolveUserGroupId}){
 const O=mongoose.Schema.Types.ObjectId;
 const examSchema=new mongoose.Schema({title:{type:String,required:true,maxlength:180},courseId:{type:O,ref:'Course',required:true},groupId:{type:O,required:true,index:true},createdBy:{type:O,ref:'User',required:true},startsAt:{type:Date,required:true},endsAt:{type:Date,required:true},durationMinutes:{type:Number,min:5,max:180,default:30},questions:[{text:{type:String,required:true},options:[String],answer:{type:Number,required:true,min:0,max:5}}],published:{type:Boolean,default:true},passScore:{type:Number,default:70,min:0,max:100},practiceOnly:{type:Boolean,default:true}},{timestamps:true});
 const attemptSchema=new mongoose.Schema({examId:{type:O,ref:'RemoteExam',required:true,index:true},studentId:{type:O,ref:'User',required:true,index:true},status:{type:String,enum:['active','paused','submitted','terminated'],default:'active'},startedAt:{type:Date,default:Date.now},endedAt:Date,answers:{type:Map,of:Number,default:{}},events:[{type:String,at:Date}],score:Number,riskScore:Number,reviewPriority:String,reason:String},{timestamps:true});
 attemptSchema.index({examId:1,studentId:1},{unique:true});
 const Exam=mongoose.models.RemoteExam||mongoose.model('RemoteExam',examSchema),Attempt=mongoose.models.RemoteExamAttempt||mongoose.model('RemoteExamAttempt',attemptSchema);
 const manager=r=>['superadmin','admin','rectorate','dean','department','teacher'].includes(r);
 const error=(res,e)=>res.status(e.status||400).json({message:e.message||'So‘rov bajarilmadi'});
 const guard=async(req,exam)=>{if(req.user.role!=='student')throw Object.assign(new Error('Talaba akkaunti kerak'),{status:403});const gid=await resolveUserGroupId(req.user);if(String(gid)!==String(exam.groupId))throw Object.assign(new Error('Boshqa guruh testi'),{status:403})};
 const safe=e=>({id:String(e._id||e.id),title:e.title,courseId:e.courseId,groupId:e.groupId,startsAt:e.startsAt,endsAt:e.endsAt,durationMinutes:e.durationMinutes,passScore:e.passScore,questionCount:e.questions.length,practiceOnly:true});
 const questions=e=>e.questions.map((q,i)=>({index:i,text:q.text,options:q.options}));
 const finish=async(a,e,reason,status='submitted')=>{if(!['active','paused'].includes(a.status))return;a.status=status;a.endedAt=new Date();a.reason=reason||'';a.score=Math.round(e.questions.reduce((n,q,i)=>n+(Number(a.answers.get(String(i)))===q.answer?1:0),0)/e.questions.length*100);const p=summarizeProctorEvents(a.events);a.riskScore=p.riskScore;a.reviewPriority=p.reviewPriority;await a.save()};
 app.get('/api/lms/remote-exams',auth,async(req,res)=>{try{let q={published:true};if(req.user.role==='student'){const gid=await resolveUserGroupId(req.user);q.groupId=gid||null}else if(req.user.role==='teacher'){const ids=await Course.find({teacherId:req.user._id}).distinct('_id');q.courseId={$in:ids}}else if(!manager(req.user.role))return res.status(403).json({message:'Ruxsat yo‘q'});const rows=await Exam.find(q).sort({startsAt:-1}).limit(100).lean();res.json(rows.map(safe))}catch(e){error(res,e)}});
 app.post('/api/lms/remote-exams',auth,async(req,res)=>{try{if(!manager(req.user.role))return res.status(403).json({message:'Ruxsat yo‘q'});const course=await Course.findById(req.body.courseId);if(!course||!course.active)throw Error('Fan topilmadi');if(req.user.role==='teacher'&&String(course.teacherId)!==String(req.user._id))return res.status(403).json({message:'Faqat o‘z faningiz'});const startsAt=new Date(req.body.startsAt),endsAt=new Date(req.body.endsAt),raw=req.body.questions;if(!Number.isFinite(+startsAt)||!Number.isFinite(+endsAt)||endsAt<=startsAt)throw Error('Vaqt noto‘g‘ri');if(!Array.isArray(raw)||raw.length<2||raw.length>100)throw Error('2–100 ta savol kerak');const qs=raw.map(q=>({text:String(q.text||'').slice(0,1000),options:(q.options||[]).map(x=>String(x).slice(0,300)),answer:Number(q.answer)}));if(qs.some(q=>!q.text||q.options.length!==4||q.options.some(x=>!x)||!Number.isInteger(q.answer)||q.answer<0||q.answer>3))throw Error('Savol, 4 variant va 0–3 javob indeksi kerak');const row=await Exam.create({title:String(req.body.title||course.title).slice(0,180),courseId:course._id,groupId:course.groupId,createdBy:req.user._id,startsAt,endsAt,durationMinutes:Math.max(5,Math.min(180,Number(req.body.durationMinutes)||30)),questions:qs});audit(req,'REMOTE_PRACTICE_EXAM_CREATE','RemoteExam',row.id);res.status(201).json(safe(row))}catch(e){error(res,e)}});
 app.post('/api/lms/remote-exams/:id/start',auth,async(req,res)=>{try{const e=await Exam.findById(req.params.id);if(!e||!e.published)return res.status(404).json({message:'Test topilmadi'});await guard(req,e);const now=Date.now();if(now<+e.startsAt||now>+e.endsAt)return res.status(409).json({message:'Test vaqti emas'});let a=await Attempt.findOne({examId:e.id,studentId:req.user._id});if(a&&['submitted','terminated'].includes(a.status))return res.status(409).json({message:'Urinish yakunlangan'});if(!a)a=await Attempt.create({examId:e.id,studentId:req.user._id,events:[]});res.json({exam:safe(e),questions:questions(e),attemptId:a.id,answers:Object.fromEntries(a.answers),status:a.status,deadline:new Date(Math.min(+e.endsAt,+a.startedAt+e.durationMinutes*60000)).toISOString()})}catch(e){error(res,e)}});
 app.post('/api/lms/remote-exams/:id/answer',auth,async(req,res)=>{try{const e=await Exam.findById(req.params.id);if(!e)return res.sendStatus(404);await guard(req,e);const a=await Attempt.findOne({examId:e.id,studentId:req.user._id});if(!a)return res.sendStatus(404);if(Date.now()>Math.min(+e.endsAt,+a.startedAt+e.durationMinutes*60000)){await finish(a,e,'Vaqt tugadi');return res.status(409).json({message:'Vaqt tugadi'})}if(a.status!=='active')return res.status(409).json({message:'Test pauzada yoki yakunlangan'});const i=Number(req.body.index),v=Number(req.body.answer);if(!Number.isInteger(i)||i<0||i>=e.questions.length||!Number.isInteger(v)||v<0||v>3)throw Error('Javob noto‘g‘ri');a.answers.set(String(i),v);await a.save();res.json({ok:true})}catch(e){error(res,e)}});
 app.post('/api/lms/remote-exams/:id/event',auth,async(req,res)=>{try{const e=await Exam.findById(req.params.id);if(!e)return res.sendStatus(404);await guard(req,e);const a=await Attempt.findOne({examId:e.id,studentId:req.user._id});if(!a)return res.sendStatus(404);if(!['active','paused'].includes(a.status))return res.json({status:a.status});const type=String(req.body.type||'');if(!PROCTOR_EVENT_TYPES.includes(type))throw Error('Hodisa noto‘g‘ri');if(a.events.length<250)a.events.push({type,at:new Date()});if(['page_hidden','window_blur','fullscreen_exit','camera_track_ended','microphone_track_ended'].includes(type))a.status='paused';const count=a.events.filter(x=>['page_hidden','fullscreen_exit','camera_track_ended','microphone_track_ended'].includes(x.type)).length;if(count>=2||['camera_track_ended','microphone_track_ended'].includes(type))await finish(a,e,'Proktor hodisasi: '+type,'terminated');else await a.save();res.json({status:a.status})}catch(e){error(res,e)}});
 app.post('/api/lms/remote-exams/:id/submit',auth,async(req,res)=>{try{const e=await Exam.findById(req.params.id);if(!e)return res.sendStatus(404);await guard(req,e);const a=await Attempt.findOne({examId:e.id,studentId:req.user._id});if(!a)return res.sendStatus(404);await finish(a,e,'Talaba topshirdi');res.json({status:a.status,score:a.score,reviewPriority:a.reviewPriority,practiceOnly:true})}catch(e){error(res,e)}});
 // Periodic server-side expiry ensures that closing the browser cannot evade termination.
 const sweep=setInterval(async()=>{try{const active=await Attempt.find({status:{$in:['active','paused']}}).limit(100);for(const a of active){const e=await Exam.findById(a.examId);if(!e)continue;const timedOut=Date.now()>Math.min(+e.endsAt,+a.startedAt+e.durationMinutes*60000);const pausedTooLong=a.status==='paused'&&Date.now()- +a.updatedAt>15000;if(timedOut||pausedTooLong)await finish(a,e,timedOut?'Vaqt tugadi':'Pauza 15 soniyadan oshdi',pausedTooLong?'terminated':'submitted')}}catch(err){console.error('remote exam sweep',err.message)}},15000);sweep.unref?.();
 app.get('/api/lms/remote-exams/:id/results',auth,async(req,res)=>{try{if(!manager(req.user.role))return res.sendStatus(403);const e=await Exam.findById(req.params.id);if(!e)return res.sendStatus(404);if(req.user.role==='teacher'){const c=await Course.findById(e.courseId);if(String(c?.teacherId)!==String(req.user._id))return res.sendStatus(403)}res.json(await Attempt.find({examId:e.id}).select('-answers').populate('studentId','fullName login').lean())}catch(e){error(res,e)}});
 return {Exam,Attempt};
}
